[package]
name = "emo-lan-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emo-lan"
path = "src/main.rs"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
common = { path = "../common" }
regex = "1.5"